# Generated by Django 4.2.30 on 2026-04-25 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('rice', 'Rice'), ('wheat', 'Wheat'), ('corn', 'Corn'), ('cotton', 'Cotton'), ('sugarcane', 'Sugarcane'), ('potato', 'Potato'), ('tomato', 'Tomato'), ('soybean', 'Soybean'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('other', 'Other')], max_length=50)),
                ('soil_condition', models.CharField(choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('loamy', 'Loamy'), ('silt', 'Silt'), ('peat', 'Peat'), ('chalk', 'Chalk'), ('other', 'Other')], max_length=50)),
                ('weather', models.CharField(choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('humid', 'Humid'), ('dry', 'Dry'), ('windy', 'Windy'), ('stormy', 'Stormy')], max_length=50)),
                ('temperature', models.FloatField(default=25.0, help_text='Temperature in °C')),
                ('humidity', models.FloatField(default=60.0, help_text='Humidity percentage')),
                ('planting_date', models.DateField()),
                ('farm_area', models.FloatField(default=1.0, help_text='Farm area in acres')),
                ('pest_image', models.ImageField(blank=True, help_text='Upload an image for pest detection', null=True, upload_to='pest_images/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farm Data',
                'verbose_name_plural': 'Farm Data Records',
                'db_table': 'farm_data',
                'ordering': ['-created_at'],
            },
        ),
    ]
