services:
  - type: web
    name: smartharvest-web
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn smart_harvest.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: DEBUG
        value: "False"
